### ISSUE TITLE
Statues all look the same even though there are different types

### ISSUE THREAD

**Issue by graves501** [sakkaku-dev/nethack-web#60]
Might be a tileset issue? This tileset file of nevanda should be pretty up-to-date -> https://nethackwiki.com/mediawiki/images/2/26/Nevanda.png

**Comment by myin142** [comment]
Nothing we can do. There is just one statue tile in the tileset

**Comment by graves501** [comment]
@myin142 I beg to differ, the statues are provided at the bottom of the tileset, but maybe something goes wrong while processing/reading the tileset file. Perhaps `BrowserHack` "suffers" from the same problem (haven't played it enough), but in `nethack-x11` there are definitely different kinds of statues that make use of the provided tileset.

![image](https://github.com/sakkaku-dev/nethack-web/assets/11211125/b15e4597-1dcf-4e69-9628-c75dbb34c7cf)

Another example of the official tileset that also provides different kind of statues ([link](https://nethackwiki.com/wiki/Tileset))

![image](https://github.com/sakkaku-dev/nethack-web/assets/11211125/9600ad9e-566e-4148-9bc2-aab80af77f2d)

**Comment by myin142** [comment]
Didn't know they all where statues. But the problem is that they are not mapped correctly. Not sure how `nethack-x11` does it, but the values in `glyph2tile` are currently not correct. They all map to one statue. This requires more digging into the c code.

Example glyph for reference:
 - statue of a lichen: glyph 5764 ->  tile 845
 - statue of grid bug: glyph 5724 -> tile 845
