### ISSUE TITLE
manually mark items cursed/uncursed

### ISSUE THREAD

**Issue by myin142** [sakkaku-dev/nethack-web#80]

**Comment by graves501** [comment]
I think this is already built in: You can annotate items with #annotate - giving you the possibility to add a description for an item e.g.:

![2023-07-17_16-15-05](https://github.com/sakkaku-dev/nethack-web/assets/11211125/aada77f2-5a16-4f00-a957-5a9797bf1a86)

It would be nice if the item would be red in the inventory because the description contains "cursed" now.
